#!/usr/bin/env python3

import corrupt_clang

import sys
import os
from argparse import ArgumentParser
import random

def parse_args(arguments):
    'Parse arguments and returned the parsed product'
    parser = ArgumentParser()
    parser.add_argument('procfiles', metavar='ProcFile', nargs='+',
                        help='''
                            The .proc files generated by the corrupt clang
                            compiler when in --capture-choices mode.  This is
                            the set of files where the random choices will be
                            made.
                            ''')
    parser.add_argument('-n', '--number', type=int, default=1000,
                        help='''
                            Number of corruption choices to make.  The default
                            is to make 1000 of them.
                            ''')
    parser.add_argument('-o', '--output', default='corruptions.sqlite',
                        help='''
                            The name of the sqlite file to use.  The default is
                            'corruptions.sqlite'.
                            ''')
    parser.add_argument('-s', '--seed', default=42,
                        help='''
                            The seed for the random number generator.  The
                            default is 42.
                            ''')
    return parser.parse_args(arguments)

def main(arguments):
    'Main logic here'
    args = parse_args(arguments)
    random.seed(args.seed)
    corrupt_clang.random.seed(args.seed)
    
    functions = corrupt_clang.parse_captured(args.procfiles)
    choices = []
    for _ in range(args.number):
        choice = choose_injection(functions)
        choices.append(
            '{x.fname},{x.func},{x.instr},{x.val},{x.op}'.format(x=choice))

    with open(args.output, 'rb') as fout:

    args.procfiles
    args.number
    args.output

if __name__ == '__main__':
    main(sys.argv[1:])
