[database]
type = 'sqlite'
filepath = 'results.sqlite'

[run]
timing = false

[[hosts]]
name = 'ray'

[hosts.dev_build]
compiler_name = 'g++'
optimization_level = '-O2'
switches = '-funsafe-math-optimizations'

[hosts.ground_truth]
compiler_name = 'g++'
optimization_level = '-O2'
switches = ''

  [[hosts.compilers]]
  binary = 'g++'
  name = 'g++'

